input_channel: 3

depth_multiple: 0.5
width_multiple: 1.0

backbone:
    # [repeat, module, args]
    [
        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        [1, Conv, [64, 3, 1, null, 1, "ReLU"]],
        [1, Conv, [48, 1, 2, null, 1, "ReLU"]],
        [1, InvertedResidualv2, [32, 3, 2]],
        [5, InvertedResidualv2, [96, 8, 2]],
        [1, Conv, [384, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, FixedConv, [6, 1, 1, null, 1]]
    ]
