input_channel: 3

depth_multiple: 0.5
width_multiple: 0.75

backbone:
    # [repeat, module, args]
    [
        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        [2, Conv, [64, 3, 1, null, 1, "ReLU"]],
        [4, Conv, [80, 1, 2, null, 1, "ReLU"]],
        [4, DWConv, [96, 5, 2, null, "Hardswish"]],
        [1, Conv, [256, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, FixedConv, [6, 1, 1, null, 1]]
    ]